source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'rails_db'
gem 'devise'
gem 'pundit'
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin.git'
gem 'inherited_resources', git: 'https://github.com/josevalim/inherited_resources.git'
gem 'slim-rails'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'cocoon'
gem 'rails-erd'
gem 'aasm'
gem 'annotate'
gem 'paperclip'
gem 'aws-sdk'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'capybara'
  gem "codeclimate-test-reporter", require: nil
  gem 'shoulda'
  gem 'rails-controller-testing'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
